CREATE TABLE IF NOT EXISTS tor_skills (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tor_id INTEGER NOT NULL,
  skill TEXT NOT NULL,
  extracted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tor_id) REFERENCES tors(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_tor_skills_tor ON tor_skills(tor_id);
